# Site settings
title: Habib's boiler plage
tagline: Testing website

url: "" # the base hostname & protocol for your site

# Used for theme in head.html, cannot be used in Stylus files
color-primary: "#263238"

# contact
author:
  name: Habib Khan
  url: http://github.com/habibkhan14

twitter_username: habibkhan14
github_username:  habibkhan14
github_url: "https://github.com/danbuckland/jekyll-holding-page-boilerplate"

# Others
markdown: redcarpet

# Exclude Stylus files, nodemodules, and gulpfile
exclude: [node_modules, gulpfile.js, styl, npm-debug.log, Gemfile, Gemfile.lock, LICENSE, README.md, package.json]
